import type { Metadata } from "next";
import "./globals.css";
import Gnb from "./components/Gnb";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <header>
                    <Gnb />
                </header>
                {children}
            </body>
        </html>
    );
}
