import Link from "next/link";
import "./globals.css";
import Control from "./Control";

export const metadata = {
    title: "Web tutorial",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const res = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", {
        // next: { revalidate: 0 },
        cache: "no-store",
    });
    const topics = await res.json();
    return (
        <html>
            <body>
                <h1>
                    <Link href="/">Web</Link>
                </h1>
                <ol>
                    {topics.map((topic) => {
                        return (
                            <li key={topic.id}>
                                <Link href={`/read/${topic.id}`}>
                                    {topic.title}
                                </Link>
                            </li>
                        );
                    })}
                </ol>
                {children}
                <Control />
            </body>
        </html>
    );
}
